REM   Script: Session 01_Activity8
REM   _Activity8

SELECT * from orders;

SELECT * from orders;

SELECT CUSTOMER_ID,MAX(PURCHASE_AMOUNT) as MAX_ORDER_AMOUNT from orders GROUP BY CUSTOMER_ID;

SELECT * from orders;

SELECT SALESMAN_ID,MAX(PURCHASE_AMOUNT) as MAX_SALE_AMOUNT from orders GROUP BY SALESMAN_ID HAVING ORDER_DATE='2012-08-17';

SELECT SALESMAN_ID,MAX(PURCHASE_AMOUNT),ORDER_DATE as MAX_SALE_AMOUNT from orders GROUP BY SALESMAN_ID HAVING ORDER_DATE='2012-08-17';

SELECT SALESMAN_ID,MAX(PURCHASE_AMOUNT),ORDER_DATE as MAX_SALE_AMOUNT from orders GROUP BY SALESMAN_ID,ORDER_DATE HAVING ORDER_DATE='2012-08-17';

SELECT SALESMAN_ID,MAX(PURCHASE_AMOUNT),ORDER_DATE as MAX_SALE_AMOUNT from orders WHERE ORDER_DATE='2012-08-17' GROUP BY SALESMAN_ID,ORDER_DATE;

SELECT * from orders;

SELECT SALESMAN_ID,ORDER_DATE,MAX(PURCHASE_AMOUNT) as MAX_SALE_AMOUNT from orders WHERE ORDER_DATE=To_DATE('2012/08/17', 'YYYY/MM/DD') GROUP BY SALESMAN_ID,ORDER_DATE;

SELECT customer_id, order_date, MAX(purchase_amount) AS "Max Amount" FROM orders 
GROUP BY customer_id, order_date 
HAVING MAX(purchase_amount) IN(2030, 3450, 5760, 6000);

